version: '3.9'

services:
  server-t:
    image: to-do-list-server-t
    build:
      dockerfile: ./server/Dockerfile.t
    tty: true
    # command: yarn test
    environment:
      - TZ=Asia/Hong_Kong
    env_file:
      - .env.test
    networks:
      - to-do-list-t

  postgres-t:
    image: postgres:15.3-alpine
    restart: always
    # ports:
    #   - $POSTGRES_PORT:5432
    env_file:
      - .env.test
    networks:
      - to-do-list-t

  redis-t:
    image: redis:6.2.13-alpine
    restart: always
    command: redis-server --include /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - $REDIS_PORT:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - to-do-list-t

networks:
  to-do-list-t:
